### ISSUE TITLE
Crash on empty filelist

### ISSUE THREAD

**Issue by ItGacky** [julianxhokaxhiu/gulp-closurecompiler#1]
gulp-closurecompiler crashes when the passed filelist is empty.
It will happen when we use it with gulp-newer or so.

Here is a makeshift fix for gulp-closurecompiler.js:

```
        beforeEnd = function() {
 +          if (files.length === 0) { this.queue(null); return; }
```

Here is trace-back on error:

```
./node_modules/gulp-closurecompiler/gulp-closurecompiler.js:50
                                                        base: firstFile.base,
                                                                       ^

TypeError: Cannot read property 'base' of undefined
    at Stream.<anonymous> (./node_modules/gulp-closurecompiler/gulp-closurecompiler.js:50:23)
    at ./node_modules/gulp-closurecompiler/node_modules/closurecompiler/ClosureCompiler.js:293:21
    at ChildProcess.<anonymous> (./node_modules/gulp-closurecompiler/node_modules/closurecompiler/ClosureCompiler.js:282:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by julianxhokaxhiu** [comment]
Thanks for the hint. Fixed and published 0.1.1
